title: Events
modelClass: AfonsoStudio\EventsSchedule\Models\Event
list: $/afonsostudio/eventsschedule/models/event/columns.yaml
recordUrl: 'afonsostudio/eventsschedule/events/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
